import Header from "./components/partials/Header";  
import Footer from "./components/partials/Footer";
import Notice from "./components/common/Notice";
export const metadata = {
  title: "AAJ Swift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Header Component */}
        <Header />
        
        {/* Main content (children will be rendered here) */}
        <main>{children}</main>
        <div className="notice-window">
          <Notice />
        </div>

        {/* Footer Component */}
        <Footer />
      </body>
    </html>
  );
}
